### ISSUE TITLE
New page/feed/feature: tradeables tagged with gem price

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#206] opened 2020-12-19 14:35 UTC
# What problem does this feature address?
Tradeables tagged with a gem value are neat, because it makes for the quickest trades ever. There's a set price, you offer it, and you get it. Hence, a big feed or a big table where all the games on the site that currently have a gem price on them, could be useful. Especially if it is possible to sort the table by price, so that people can snag up all those 150 gem games when they are new and just want a lot of games.

## Describe a solution
So yeah, basically: I just want a list/table/feed with all tradeables tagged with the Gems trading tag, and sort it by value. 

It could also be a Discord feed --> Every time a new tradable is tagged with a gem price, throw it into the Discord feed.

**Comment by bartervg** [comment] 2021-01-24 16:28
bartervg/barter.vg#35

**Comment by Luckz** [comment] 2021-01-26 21:17
Somewhat of a duplicate of 35, in that it calls for a global value-sortable price list as well.

Barter is not the DIG marketplace. Does it want to be?

**Comment by Tecfan** [comment] 2021-01-26 22:06
It doesn't make it a marketplace, it's just arranging info that already exists into logical tables.

**Comment by bartervg** [comment] 2021-01-26 22:23
> It doesn't make it a marketplace, it's just arranging info that already exists into logical tables.

semantics

There is a potential marketplace feature. Rather than have it sort of partially implemented on barter.vg, someone should attempt to fully do it on a dedicated site for it.

**Comment by bartervg** [comment] 2021-01-27 18:19
It's up at https://notamarketplace.com/ 

Don't like it? It's FOSS and the site builds from the Github repo https://github.com/bartervg/notamarketplace

**Comment by Tecfan** [comment] 2021-01-27 18:48
Haha, you absolute mad lad.

**Comment by bartervg** [comment] 2021-01-28 01:39
Out of Barter Scope. Divert related issues to dedicated project https://github.com/bartervg/notamarketplace

**Closed by bartervg** 2021-01-28 01:39 UTC
Labels: enhancement, help wanted, out of scope
