### ISSUE TITLE
Proposal: Partially-completed offers should have a time limit

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#304] opened 2022-12-16 23:37 UTC
# Proposal
After one side completes an offer, there should be a limited amount of time for the other side to act, either to select completed or failed. If the other side does not act by the deadline, the offer would become inactive, and the other side could no longer fail the offer.

# Rationale
When one side completes an offer, the offer has no expiration and will remain in that state indefinitely. This can be annoying for the side that completed the offer. In addition, it leaves the completing user open to disputes months or years after the exchange. 

Other platforms like eBay and Airbnb have time limits on when feedback can be provided. 

There are around 400 offers on Barter that partially-completed. This proposal would affect those 400 and any future offers where one side clicked completed.

**Comment by arseny92** [comment] 2022-12-17 02:09
#duplicate of #226

**Closed as completed** 2022-12-17 14:35 UTC
Labels: duplicate, Proposal
