### ISSUE TITLE
Mandatory choice

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#17] opened 2019-07-01 23:17 UTC
Add an option/checkmark to make a tradable in list of choices in an offer mandatory to pick. E.g. I absolutely want this game, and some other of your games, for my game.

**Comment by bartervg** [comment] 2019-07-02 02:19
this is the required attribute on the API

**Comment by Revadike** [comment] 2019-07-02 11:16
Now, it still needs to be added to the UI.

**Comment by Tecfan** [comment] 2021-01-17 09:16
My issue #125 seems to be a duplicate of this. 

This function is now implemented and working great for me, but it is only activated for certain users (me?) it seems.

**Comment by bartervg** [comment] 2022-12-27 13:30
> This function is now implemented and working great for me, but it is only activated for certain users (me?) it seems.

The UI is visible for everyone now. Although I don't think `&` is intuitive. 

![image](https://user-images.githubusercontent.com/28576132/209673563-7d7486d3-69e0-44c4-ac2a-9427b8806cde.png)

**Closed by bartervg** 2022-12-27 13:30 UTC
Labels: enhancement

**Comment by bartervg** [comment] 2022-12-27 13:33
#125 will stay open for the `combo` function

**Comment by Revadike** [comment] 2022-12-27 18:45
> > This function is now implemented and working great for me, but it is only activated for certain users (me?) it seems.
> 
> The UI is visible for everyone now. Although I don't think `&` is intuitive.
> 
> ![image](https://user-images.githubusercontent.com/28576132/209673563-7d7486d3-69e0-44c4-ac2a-9427b8806cde.png)

How about a lock 🔒?

**Comment by bartervg** [comment] 2022-12-27 19:15
> How about a lock 🔒?

To me,🔒seems to connote the opposite, that it's unavailable. Also, I may use 🔒for a future offer feature.

**Comment by Revadike** [comment] 2022-12-27 19:18
No, intuitively that seems like a locked/mandatory choice to me

**Comment by bartervg** [comment] 2022-12-27 20:00
> No, intuitively that seems like a locked/mandatory choice to me

Yes, if you add `locked` to the term, then🔒 seems to be intuitive. 

This will devolve into a semantic critique, but is there not an internal contradiction in the term `mandatory choice`?

**Comment by Revadike** [comment] 2022-12-27 20:06
mandatory choice = required
