### ISSUE TITLE
Track prices more accurately

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#32] opened 2019-11-02 17:13 UTC
Perhaps even go as far as to track steam sales.
You can get the data directly from Steam or ITAD.

**Comment by Luckz** [comment] 2019-12-05 15:42
Sales are IMO out of scope. With the other, I guess the problems you are referring to are inaccurate prices and sub prices?

**Comment by Revadike** [comment] 2019-12-05 15:48
> Sales are IMO out of scope. With the other, I guess the problems you are referring to are inaccurate prices and sub prices?

Maybe request them from ITAD instead? They include sales.

**Comment by bartervg** [comment] 2019-12-09 13:45
The prices are tracked, but not displayed (other than JSON). As luckz stated, that isn't the focus, but perhaps current prices (+/- 12 hours) will appear in a layout update.

**Comment by Revadike** [comment] 2019-12-09 13:46
Oh really? So it's just a matter of displaying the data? That shouldn't be a challenge, right?

**Comment by bartervg** [comment] 2019-12-09 16:51
It depends on what data you're expecting. I prefer ITAD price charts and I don't plan to track that much data. However, if you want basic `-20% now` then it won't be a challenge.

**Comment by bartervg** [comment] 2019-12-09 17:54
Price data is several weeks stale. I don't know the cause yet. However, price (weeks old) is displayed on the profile page now. 
![image](https://user-images.githubusercontent.com/28576132/70459865-11ce6b80-1a83-11ea-884e-ea770e9f2248.png)

**Comment by bartervg** [comment] 2020-01-04 09:07
Price sync appears to be working again. Higher-prices and lowest-prices channels on Discord updated frequently during the sale. I spot checked games from the Steam Specials list and games that are no longer on sale and the prices were correct.

**Closed by bartervg** 2020-01-04 09:07 UTC
Labels: bug, enhancement

**Comment by Revadike** [comment] 2020-01-04 14:18
so the updated prices will be displayed now?

**Comment by bartervg** [comment] 2020-01-06 14:08
They've been displayed, but the price data was several weeks stale stale. The bug fix was ensuring that the price sync wouldn't get stuck in an endless loop of checking prices for games that do not have prices.

Where would you like to see the price information?

**Comment by Revadike** [comment] 2020-01-06 14:16
> Where would you like to see the price information?

where the price is usually displayed

**Comment by bartervg** [comment] 2020-01-06 14:23
![image](https://user-images.githubusercontent.com/28576132/71823818-28f28000-3066-11ea-9533-ed27e5cc3f91.png)
The green 31.99 next to the history link at the bottom.
